"use client"
import { BodyContainer } from "./styles/global.styled"; 
export const experimental_ppr = true;
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",}

import Image from "next/image";
import Link from 'next/link'
import { HeaderContainer, LogoBlock, LogoTitle, LinksBlock, LinkStyle } from "./styles/header.styled"; 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <BodyContainer>
    <HeaderContainer>
        <Link href="/" style={{textDecoration: "none"}}>
          <LogoBlock>
              <Image
                src="/nextjs.svg"
                alt="nextjs logomark"
                width={60}
                height={60}
                priority={false}
              />
              <LogoTitle>NextJS</LogoTitle>
          </LogoBlock>
        </Link>
        <LinksBlock>
          <Link href="/products" passHref legacyBehavior><LinkStyle>Products</LinkStyle></Link>
          <Link href="/pricing" passHref legacyBehavior><LinkStyle>Pricing</LinkStyle></Link>
          <Link href="/docs" passHref legacyBehavior><LinkStyle>Docs</LinkStyle></Link>
          <Link href="/company" passHref legacyBehavior><LinkStyle>Company</LinkStyle></Link>
        </LinksBlock>
        <LinksBlock>
          <Link href="/login" passHref legacyBehavior><LinkStyle>Log in</LinkStyle></Link>
          <Link href="/signup" passHref legacyBehavior><LinkStyle>Sign up</LinkStyle></Link>
        </LinksBlock>
      </HeaderContainer>
      {children}
    </BodyContainer>
    </html>
  );
}
